### ISSUE TITLE
couldn't find 'idioms_pretrain.json' in  ChID-Dataset, besides .csv files in competition directory

### ISSUE THREAD

**Issue by starry-y** [VisualJoyce/ChengyuBERT#1]
couldn't find 'idioms_pretrain.json' in  ChID-Dataset, besides .csv files in competition directory

**Comment by VisualJoyce** [comment]
Please refer to the commit of https://github.com/chujiezheng/ChID-Dataset/commit/bddaeebc4d6fc476a2a4fef541dd62a3b0b8901b

I am not sure if the links are still available.

**Comment by VisualJoyce** [comment]
You may download the [idioms_pretrain.json](https://drive.google.com/file/d/1rcHa5NQloQOr2vc-F0WXrsdOYKvY_ySi/view?usp=sharing).

**Comment by starry-y** [comment]
Thanks for your reply. But, I couldn't open the link of &nbsp;idioms_pretrain.json&nbsp;because&nbsp;Access denied.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VisualJoyce/ChengyuBERT"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月31日(星期四) 下午5:01
收件人:&nbsp;"VisualJoyce/ChengyuBERT"<ChengyuBERT@noreply.github.com&gt;;
抄送:&nbsp;"安于现状是种幸福丶"<253641340@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [VisualJoyce/ChengyuBERT] couldn't find 'idioms_pretrain.json' in  ChID-Dataset, besides .csv files in competition directory (#1)





 
You may download the idioms_pretrain.json.

**Comment by VisualJoyce** [comment]
You can download the [idioms_pretrain.json](https://drive.google.com/file/d/151LZdtYsXjqP6wTHIp0c0kL3uf13_4wG/view?usp=sharing).

**Comment by starry-y** [comment]
Thank you very much!!! It works!
Do you have the links of .csv files? Thanks very much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VisualJoyce/ChengyuBERT"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月31日(星期四) 下午5:04
收件人:&nbsp;"VisualJoyce/ChengyuBERT"<ChengyuBERT@noreply.github.com&gt;;
抄送:&nbsp;"安于现状是种幸福丶"<253641340@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [VisualJoyce/ChengyuBERT] couldn't find 'idioms_pretrain.json' in  ChID-Dataset, besides .csv files in competition directory (#1)





 
You can download the idioms_pretrain.json.

**Comment by VisualJoyce** [comment]
If the original links are not accessible from Tsinghua, we recommend you to contact the original author of ChID first in case that the data may subject to copyright restrictions.

**Comment by starry-y** [comment]
ok! Thanks ~!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VisualJoyce/ChengyuBERT"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月31日(星期四) 下午5:31
收件人:&nbsp;"VisualJoyce/ChengyuBERT"<ChengyuBERT@noreply.github.com&gt;;
抄送:&nbsp;"安于现状是种幸福丶"<253641340@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [VisualJoyce/ChengyuBERT] couldn't find 'idioms_pretrain.json' in  ChID-Dataset, besides .csv files in competition directory (#1)





 
If the original links are not accessible from Tsinghua, we recommend you to contact the original author of ChID first in case that the data may subject to copyright restrictions.
