### ISSUE TITLE
请问TxtLmdb和TxtTokLmdb这两个类是用来做什么的呢

### ISSUE THREAD

**Issue by starry-y** [VisualJoyce/ChengyuBERT#10]

**Comment by VisualJoyce** [comment]
预处理的结果存储和读取，这里用了`lmdb`.

**Comment by starry-y** [comment]
这个data.mdb文件里面是长什么的呢？
是不是每个example都有一个字典，字典的键是图片里绿色的这些
![image](https://user-images.githubusercontent.com/57939349/112949949-53998e80-916c-11eb-955b-30d7a8bd30ca.png)

**Comment by VisualJoyce** [comment]
是在此之前的，里面存储的是以下内容

https://github.com/VisualJoyce/ChengyuBERT/blob/2d19da89949c6cc9165e18d5a33ac29dbceae921/preprocess.py#L345-L353

**Comment by starry-y** [comment]
我想通过键来读取值，采用的是以下代码，但是他返回的Traceback意思是没有'options'这个键，是不是我读取的方式有问题呢？
db_dir是存放data.mdb的文件夹路径
`
env = lmdb.open(db_dir, readonly=True,create=False,lock=False,readahead=True)
key = 'options'
print(msgpack.loads(decompress(txn.get(key.encode('utf-8'))),raw=False))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: a bytes-like object is required, not 'NoneType'
`

**Comment by VisualJoyce** [comment]
存储的时候不是按照`options`存的，这里的`key`不对。应该传的是样本的`id`。

**Comment by starry-y** [comment]
嗯嗯！ 输出了！感谢！

**Comment by VisualJoyce** [comment]
不客气！
