### ISSUE TITLE
About modeling.

### ISSUE THREAD

**Issue by WinniyGD** [VisualJoyce/ChengyuBERT#13]
Sry, I have one more question about the codes. 

What's the difference or purpose among the following model classes:

@register_model('chengyubert-2stage-stage2-mask')
@register_model('chengyubert-2stage-stage2-cls')
@register_model('chengyubert-2stage-stage2-window')
@register_model('chengyubert-2stage-stage2-mask-window')

**Comment by VisualJoyce** [comment]
These were for ablation studies. But I find some of them are not significant enough.

**Comment by WinniyGD** [comment]
OK, could you share the 33237 vocabulary and it's dataset ?

**Comment by VisualJoyce** [comment]
> You can download the [idioms_pretrain.json](https://drive.google.com/file/d/151LZdtYsXjqP6wTHIp0c0kL3uf13_4wG/view?usp=sharing).

**Comment by WinniyGD** [comment]
Thx !   It was really helpful.  👍

**Comment by WinniyGD** [comment]
Sry, I wanna know the relation between embedding index and idioms id.
![image](https://user-images.githubusercontent.com/70563473/114488827-a54e1880-9c44-11eb-8ed0-da67604e6765.png)
![image](https://user-images.githubusercontent.com/70563473/114488894-c1ea5080-9c44-11eb-9ec0-0c0628009323.png)
It means the 0-3847(index) embedding is ChID idioms embedding ?
The file 'idioms_pretrain.json' does not show the idiom id. How to get the one-to-one correspondence?

**Comment by VisualJoyce** [comment]
It's constructed via:

https://github.com/VisualJoyce/ChengyuBERT/blob/2d19da89949c6cc9165e18d5a33ac29dbceae921/chengyubert/data/__init__.py#L115-L143

**Comment by WinniyGD** [comment]
Oh！Amazing！Thank for your patience！
