### ISSUE TITLE
accuracy

### ISSUE THREAD

**Issue by starry-y** [VisualJoyce/ChengyuBERT#14]
你好，我用你放出来的2stage_stage1_wwm_ext训练了第二阶段的official ‘chengyubert-2stage-stage2’，结果只有77。按照您_A BERT-based Two-Stage Model for Chinese Chengyu Recommendation_Table4的结果，应该是85.43吧。请问为什么会差这么多呢，是我哪里没有注意到吗？

**Comment by VisualJoyce** [comment]
几块gpu，训练参数是怎样的？

**Comment by starry-y** [comment]
2块gpu，我设置的训练steps不是25000而是50000，其他的参数和你在readme里面给的是一样的。我在48000的时候达到的77

**Comment by VisualJoyce** [comment]
梯度累积设置大一点，比如5，看看行不行

**Comment by starry-y** [comment]
好的我试一下。我看您论文里的最好结果是86.15，对应是在original的情况下得到的吗

**Comment by VisualJoyce** [comment]
combined和enlarged差不多，应该都能达到类似水平

**Comment by starry-y** [comment]
感谢您的回复！

**Comment by starry-y** [comment]
还是不行，根本达不到78
请问要用您的2stage_stage1_wwm_ext重新preprocessing

**Comment by VisualJoyce** [comment]
你使用的命令行发一下

**Comment by VisualJoyce** [comment]
配置文件也发一下

**Comment by starry-y** [comment]
我重新下载了您的仓库 目前已达到80
抱歉耽误您的时间了 
感谢您的答复

**Comment by VisualJoyce** [comment]
那就好，哈哈
