### ISSUE TITLE
The config of  chengyubert_2stage_stage1

### ISSUE THREAD

**Issue by 02hyc** [VisualJoyce/ChengyuBERT#25]
Hello! I want to load the model in https://huggingface.co/visualjoyce/chengyubert_2stage_stage1_wwm_ext/tree/main
However, the config says that the len_idiom_vocab is 33237, the vocab.txt supported in the link isn't the idioms' vocab and the size of the vocab.txt isn't 33237. I find in the Google Drive you in README, and find a file "idioms_pretrain.json", but the size of this file is 33238. So can you tell me, to load the model in the huggingface, what vocab should I use?

**Comment by Vimos** [comment]
The vocab is constructed from these files, please refer to https://github.com/VisualJoyce/ChengyuBERT/blob/88dbc1cd4c6904133b3363248f2bdc5cc10a9099/chengyubert/data/__init__.py#L116C1-L144C25
