### ISSUE TITLE
How many steps does it save the model?

### ISSUE THREAD

**Issue by chenzhengdeeplearning** [VisualJoyce/ChengyuBERT#3]
I have trained 19552 steps, and only have outputs of log.
There are no ckpts.
Is that right? 

file:///home/chen/mydisk/2021-01-05%2012-53-53%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png

**Comment by VisualJoyce** [comment]
There is one parameter called `valid_steps`, all the checkpoints will be saved to `data/output/<model>/ckpt`.

**Comment by chenzhengdeeplearning** [comment]
My valid_steps is 1000, and there are no ckpt files.
Something goes wrong.
When I met the problem with log earlier, I commented out some codes, is that wrong? Here is my code in chengyubert/utils/save.py

`def save_training_meta(args):
    if args.rank > 0:
        return

    os.makedirs(join(args.output_dir, 'log'), exist_ok=True)
    os.makedirs(join(args.output_dir, 'ckpt'), exist_ok=True)

    with open(join(args.output_dir, 'log', 'hps.json'), 'w') as writer:
        json.dump(vars(args), writer, indent=4)

    if os.path.isfile(args.model_config):
        model_config = json.load(open(args.model_config))
        with open(join(args.output_dir, 'log', 'model.json'), 'w') as writer:
            json.dump(model_config, writer, indent=4)
    # git info
    # try:
    #     LOGGER.info("Waiting on git info....")
    #     c = subprocess.run(["git", "rev-parse", "--abbrev-ref", "HEAD"],
    #                        timeout=10, stdout=subprocess.PIPE)
    #     git_branch_name = c.stdout.decode().strip()
    #     LOGGER.info("Git branch: %s", git_branch_name)
    #     c = subprocess.run(["git", "rev-parse", "HEAD"],
    #                        timeout=10, stdout=subprocess.PIPE)
    #     git_sha = c.stdout.decode().strip()
    #     LOGGER.info("Git SHA: %s", git_sha)
    #     git_dir = abspath(dirname(__file__))
    #     git_status = subprocess.check_output(
    #         ['git', 'status', '--short'],
    #         cwd=git_dir, universal_newlines=True).strip()
    #     with open(join(args.output_dir, 'log', 'git_info.json'),
    #               'w') as writer:
    #         json.dump({'branch': git_branch_name,
    #                    'is_dirty': bool(git_status),
    #                    'status': git_status,
    #                    'sha': git_sha},
    #                   writer, indent=4)
    # except subprocess.TimeoutExpired as e:
    #     LOGGER.exception(e)
    #     LOGGER.warn("Git info not found. Moving right along...")`

**Comment by VisualJoyce** [comment]
Can you post your directory tree of `data/output`?

**Comment by chenzhengdeeplearning** [comment]
![图片](https://user-images.githubusercontent.com/43208141/103609613-2ec0c100-4f59-11eb-9eda-f907cf3b5180.png)

**Comment by VisualJoyce** [comment]
Strange. The code commented out is not related to saving models. But your directory tree has no `ckpt` and `results` sub-directory. You may need to check if https://github.com/VisualJoyce/ChengyuBERT/blob/7e4c20a399ba79c106e9d8e53fcd20b5d63a7a7d/train_official.py#L49-L52 are still active.

**Comment by chenzhengdeeplearning** [comment]
The codes in that four lines are not changing before, so they are the same with yours. Could you post your output directory?

**Comment by chenzhengdeeplearning** [comment]
![图片](https://user-images.githubusercontent.com/43208141/103612196-df7d8f00-4f5e-11eb-95fb-a38fcd64510a.png)
Is that right?
Actually, my codes couldn't read the values of train-official-bert-base-1gpu.json and terminal input, so I put the value into train_official.py.
What hyper-parameters should I follow? 
The ones in train-official-bert-base-1gpu.json?

**Comment by VisualJoyce** [comment]
This is the supposed output. Use the command line in readme should work.

**Comment by chenzhengdeeplearning** [comment]
Thanks a lot!
