### ISSUE TITLE
Error when train Bert-chid

### ISSUE THREAD

**Issue by starry-y** [VisualJoyce/ChengyuBERT#6]
```bash
Traceback (most recent call last):                                                                                      | 0/24822 [00:00<?, ?it/s]
  File "train_official.py", line 470, in <module>
    main(args)
  File "train_official.py", line 317, in main
    best_ckpt = train(model, dataloaders, opts)
  File "train_official.py", line 145, in train
    opts, global_step)
  File "train_official.py", line 235, in evaluation
    log.update(validate(opts, model, loader, split, global_step))
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "train_official.py", line 177, in validate
    loss = F.cross_entropy(logits, targets, reduction='sum')
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/functional.py", line 2422, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/functional.py", line 2228, in nll_loss
    out_size, target.size()))
ValueError: Expected target size (72, 1), got torch.Size([72])

```

**Comment by VisualJoyce** [comment]
I uploaded the Readme. Can you try the following?

```
CUDA_VISIBLE_DEVICES=0,1,2,3 CONFIG_FILE="train-official-bert-base-1gpu.json" \
bash docker_train.sh official \
"MODEL=chengyubert-cloze ENLARGED_CANDIDATES=0 LEARNING_RATE=0.0001 NUM_TRAIN_STEPS=15003 GRADIENT_ACCUMULATION_STEPS=1 VALID_STEPS=100 GRAD_NORM=1"
```

I tested locally, it should be able to run.

**Comment by starry-y** [comment]
I tried and there is an error never met before.
In the json file, `"dataset_cls": "chengyu-masked"`
So there is an error about masked.py
`
File "train_official.py", line 302, in main
    splits, dataloaders = create_dataloaders(LOGGER, DatasetCls, EvalDatasetCls, opts)
  File "/src/chengyubert/data/__init__.py", line 169, in create_dataloaders
    dataloaders[split] = create_dataloader(txt_db, batch_size, 'train' == split, dataset_cls, opts)
  File "/src/chengyubert/data/__init__.py", line 122, in create_dataloader
    dset = dset_cls(txt_path, opts.max_txt_len, opts)
  File "/src/chengyubert/data/dataset/masked.py", line 20, in __init__
    with open('/annotations/synonyms/chengyu_synonyms_recall_filter.json') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/annotations/synonyms/chengyu_synonyms_recall_filter.json'

`

**Comment by starry-y** [comment]
I changed the model from "dual" to "cloze"
Then error is gone.

**Comment by starry-y** [comment]
Should I download chengyu_synonyms_recall_filter.json ?

**Comment by VisualJoyce** [comment]
I have deleted that code, it's not related to this project.

**Comment by starry-y** [comment]
How about `"eval_dataset_cls": "chengyu-masked-eval"`?
Should I delete this line in json file too ?

**Comment by VisualJoyce** [comment]
This is required, please keep them.

**Comment by starry-y** [comment]
ok!!!

**Comment by starry-y** [comment]
If I detele `dataset_cls": "chengyu-masked ` in json file.
Then...
`
File "train_official.py", line 300, in main
    DatasetCls = DATA_REGISTRY[opts.dataset_cls]
AttributeError: 'Namespace' object has no attribute 'dataset_cls'

`
Should I replace chengyu-masked to sth else?

**Comment by VisualJoyce** [comment]
That's strange.

**Comment by VisualJoyce** [comment]
Can you pull the code and try again? I tested locally, it should be OK.

**Comment by starry-y** [comment]
I delete dataset_cls": "chengyu-masked in json file.
`File "train_official.py", line 300, in main
DatasetCls = DATA_REGISTRY[opts.dataset_cls]
AttributeError: 'Namespace' object has no attribute 'dataset_cls'`

Add this line.
`FileNotFoundError: [Errno 2] No such file or directory: '/annotations/synonyms/chengyu_synonyms_recall_filter.json'`

In the file of train_official.py
299-302 line
`# data loaders
    DatasetCls = DATA_REGISTRY[opts.dataset_cls]
    EvalDatasetCls = DATA_REGISTRY[opts.eval_dataset_cls]
    splits, dataloaders = create_dataloaders(LOGGER, DatasetCls, EvalDatasetCls, opts)`

It does need a value of `opts.dataset_cls`...

**Comment by VisualJoyce** [comment]
Can you confirm that your head info?
```
git rev-parse --short HEAD
b5e1aed
```

**Comment by starry-y** [comment]
fatal: Not a git repository (or any parent up to mount point /home/mydisk)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

**Comment by VisualJoyce** [comment]
So you are not using git.

**Comment by starry-y** [comment]
So... I should git clone now?
orz...

**Comment by VisualJoyce** [comment]
I don't quite understand. 

If you don't want to use git, then you can download the zip with the hash tag I posted.

**Comment by starry-y** [comment]
It does work.
I didn't noticed that you have changed the files..
Thanks for your patience very much!

**Comment by VisualJoyce** [comment]
Notice that this code has changed in many ways, I guess there are more issues to come. 

For example, I renamed 
* `ENLARGED_CANDIDATES=0` to `CANDIDATES=original`
* `ENLARGED_CANDIDATES=1` to `CANDIDATES=combined`

When I have time, I will update the documentation.

**Comment by starry-y** [comment]
It's lucky that it still working !
Thanks a lot
