### ISSUE TITLE
Can we remove docker and horovod ?

### ISSUE THREAD

**Issue by WinniyGD** [VisualJoyce/ChengyuBERT#7]
For some special reasons, I can't use docker and horovod. 

Can I remove them?

**Comment by VisualJoyce** [comment]
Yes, you can try the code in a way best for you. That might cost you some time to test though.

**Comment by WinniyGD** [comment]
I wanna know whether you can make a simple version？ You will be more familiar with and faster than us to complete.

**Comment by VisualJoyce** [comment]
Sorry. For this repo, we currently have no enough hands to work on a new version.

**Comment by WinniyGD** [comment]
ok, fine.

how can i instead of the following codes if removing the horovod? 

`    rank = hvd.rank()
    opts.rank = rank
    opts.size = hvd.size()`

opts.rank = ?
opts.size = ?

**Comment by VisualJoyce** [comment]
I really want to help. However, I think there might be no short answer when we migrate a code.

**Comment by WinniyGD** [comment]
Could you show me their values during the debug process ?

**Comment by VisualJoyce** [comment]
If you are using a single GPU, you can install horovod, `HOROVOD_PARA` is not passed to the program, horovod can be ignored.

If you have to avoid horovod, then `rank` is the current GPU's index, with a single card it should be 0. `size` is the GPU number in the cluster, should be 1.

**Comment by WinniyGD** [comment]
Ok, thank you very much. It works.
