### ISSUE TITLE
dropout

### ISSUE THREAD

**Issue by starry-y** [VisualJoyce/ChengyuBERT#8]
请问在modeling_bert.py，ChengyuBertForClozeChid类的前向传播中，`pooled_output = self.dropout(multiply_result)`，这个地方为什么要对乘积之后的结果进行dropout呢，能谈谈您的想法吗？

**Comment by VisualJoyce** [comment]
这个是我复制的ChID的实现，dropout一般用于防止过拟合，可以让分类器更稳定。

**Comment by starry-y** [comment]
没加入enlarged candidate的时候，在计算损失时，这个答案targets是什么维度的呢，他是在哪里被导入的呢

**Comment by VisualJoyce** [comment]
这个首先看到预处理
https://github.com/VisualJoyce/ChengyuBERT/blob/c41dfd27d0dfa1fd8dbec5173b8a3bbd96c3156a/preprocess.py#L135-L139
保存的是`options` 和 `label` (下标)。
https://github.com/VisualJoyce/ChengyuBERT/blob/c41dfd27d0dfa1fd8dbec5173b8a3bbd96c3156a/preprocess.py#L351-L352
https://github.com/VisualJoyce/ChengyuBERT/blob/c41dfd27d0dfa1fd8dbec5173b8a3bbd96c3156a/chengyubert/data/dataset/masked.py#L60-L61

https://github.com/VisualJoyce/ChengyuBERT/blob/c41dfd27d0dfa1fd8dbec5173b8a3bbd96c3156a/chengyubert/models/modeling_bert.py#L78-L81

这样就顺起来了，选择部分直接用`target`，扩展到全部成语要经过一步转换`gather`，从下标转换成成语的序号。

至于维度，你可以`print`一下，比较直接。

**Comment by starry-y** [comment]
十分感谢！
我好好学习一下！

**Comment by starry-y** [comment]
请问id2len.json是什么

**Comment by VisualJoyce** [comment]
是context的长度反查表

**Comment by starry-y** [comment]
请问怎么得到这个文件呢？

**Comment by VisualJoyce** [comment]
这个预处理生成的

**Comment by starry-y** [comment]
谢谢！已经找到！
